services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"

  alloy:
    image: grafana/alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock

  log-generator:
    image: busybox
    command: sh -c 'while true; do echo "INFO user login ok"; sleep 2; echo "ERROR database connection failed"; sleep 3; done'

volumes:
  grafana-data:
